num1 = int(input("enter first numbers :"))
num2 = int(input("enter secound number:"))
print("addition:", num1 + num2)
print("substraction:", num1 - num2)
print("multiplication", num1 * num2)
print("division", num1 / num2)