import pandas as pd
df = pd.read_csv("jojo_dataset.csv")
#whole dataset
print(df.mean(numeric_only=True))
print(df.sum(numeric_only=True))
print(df.min(numeric_only=True))
print(df.max(numeric_only=True))
print(df.count(numeric_only=True))
#single column
print(df["Power"].mean(numeric_only=True))
print(df["Speed"].sum(numeric_only=True))
print(df["Range"].min(numeric_only=True))
print(df["Durability"].max(numeric_only=True))
print(df["Potential"].count)
# by grouping
group = df.groupby("Part")
print(group["Power"].mean())
print(group["Power"].median())
print(group["Power"].min())
print(group["Power"].max())
print(group["Power"].sum())
print(group["Power"].count())
print(group["Power"].std())
print(group["Speed"].mean())
print(group["Speed"].sum())
print(group["Speed"].min())
print(group["Speed"].max())
print(group["Speed"].count())
print(group["Range"].mean())
print(group["Range"].sum())
print(group["Range"].min())
print(group["Range"].max())